version: '3'
services:
  mytomcat:
    build:
      context: ./
      dockerfile: Dockerfile-conf-working
    ports:
      - "8080:8080"
    depends_on:
      - redis
  mytomcat2:
    build:
      context: ./
      dockerfile: Dockerfile-conf-working
    ports:
      - "9090:8080"
    depends_on:
      - redis
  redis:
    image: redis:7.2
    ports:
      - 6379:6379
  proxy:
    image: nginx
    ports:
      - "3000:3000"
    links:
      - mytomcat
    depends_on:
      - mytomcat
      - mytomcat2
    volumes:
      - ./conf-working/nginx.conf:/etc/nginx/nginx.conf
