FROM tomcat:9.0.84-jdk11-corretto

RUN ["rm", "-fr", "/usr/local/tomcat/webapps/ROOT"]
COPY ./target/simplemvcjsp.war /usr/local/tomcat/webapps/ROOT.war
COPY ./lib/ /usr/local/tomcat/lib/
COPY ./conf-working/context.xml /usr/local/tomcat/conf/context.xml
COPY ./conf-working/redisson.conf /usr/local/tomcat/redisson.conf
